### ISSUE TITLE
How to add shadow?

### ISSUE THREAD

**Issue by tajjacob** [NouzNoushad/ticket_clippers#1]
How to add shadow?
Can you add parameter to add shadow?

**Comment by NouzNoushad** [comment]
Yes, I do my best.

**Comment by NouzNoushad** [comment]
@tajjacob Can you check new version of ticket_clippers. I have added box shadow parameter and also border radius parameter for shadow.

**Comment by tajjacob** [comment]
@NouzNoushad already updated to latest version. Good job brother!
